Eclipse-Station/NEV-Northern-Light

code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/update_icons.dm
* Fixes Unathi sprites using wrong sprite files.
I did what I could to try to pin down the layering issue. The species' stock tail is on the correct layer, but the custom tails are not. I don't know why this is, and I've hit a brick wall tracking it down.
=> Unathi sprite fixes, part 1

code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm
It adds a Copy Slot button on the character creator menu. The button opens up a dialogue box asking for the user to select a profile to overwrite with their currently selected character. Once selected, the user then has to click Save Slot to save that same character to the new slot. 
The dialogue box shows the names of the currently saved characters in order to avoid accidental overwriting of an existing saved character.
Closes #32 
You can quickly and easily make multiple copies of the same character for minor changes.
:cl:
add: Added a "Copy Slot" button in the character creator menu.
/:cl:
=> Adds a "Copy Slot" button to the character menu, as requested in #32

code/modules/paperwork/paperbin.dm
- Paper bins will now display the correct sprite when there is paper in it or when it's empty.
- Paper bins will no longer claim to be empty upon server start.
- Paper bin sprites will now automatically update after a piece of paper is taken out or placed inside it.
Closes #235 
Fixes an issue that prevented players from getting paper out of paper bins.
:cl:
fix: Fixed paper bins not allowing players to take paper out of them.
/:cl:
=> Fixed paper bin sprites and messages.

code/game/gamemodes/events/weather/rad_storm.dm
This adds deepmaint to the list of areas not affected by the radiation storm event. It's a little silly that an area <b>deeper inside the ship</b> has no protection from a passing radiation field.
It means you won't get totally screwed if you happen to be a little lost when the ship enters a radiation belt. It doesn't seem like the kind of danger intended for that location.
:cl:
tweak: the innermost guts of the ship are no longer open to radstorms when they happen
/:cl:
=> shields deep maint from radiation storms

code/__DEFINES/jobs.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/new_player/new_player.dm
The player's currently selected character and their occupation will be displayed on the Main Menu for a quick reminder, without having to open the Character Setup menu to check. Their occupation will be in their department's respective colour.
All roles have been tested and an automatic refresher has been added so that it syncs correctly when loading a new character or saving changes to a current character's occupation.
(Big thanks to Kicks for helping me out!)
It adds a quality of life change.
:cl:
add: Currently selected character and their occupation is now displayed on the main menu.
/:cl:
=> Current Character and occupation display on Main Menu

cev_eris.dme, zzz_modular_eclipse/storytellers/tyrant.dm
It adds a PvE (Player-versus-Environment) storyteller to the roster 
It will give players the option to activate a harsh storyteller that tries to kill them without having to worry about the paranoia involved with traitors, changelings and the occasional blitzshell mucking things up for everyone. It is meant to be quite difficult and should probably not be turned on without a full complement of departmental crew.
:cl:
add: Tyrant storyteller
/:cl:
=> adds tyrant storyteller

code/controllers/configuration_eclipse.dm, code/game/gamemodes/storyteller.dm, code/game/jobs/job/captain.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/jobs/job/silicon.dm, code/modules/mob/living/carbon/human/human.dm, config/example/config_eclipse.txt
Single-barrel names now display properly when playing as Captain or literally any of Security.
Applies whitelisting and adds in a config option to bypass head of staff requirement.
*Note: In this screenshot, all whitelists are enabled. The whitelisting is divided between silicons, heads of staff, and security - each is separate.
нестор мап
config: Adds configuration entries. Update config_eclipse.txt as necessary.
add: Implements whitelists.
fix: Aegis name prefixes should now play nice(r) with single-barrel names.
/:cl:
=> Whitelists jobs, patch for Aegis name prefixes

code/controllers/subsystems/migration.dm, code/modules/hydroponics/spreading/spreading_growth.dm
Caps maintenance fungus spreading at roughly 60 per hour.
tweak: Maintenance mushrooms should no longer overwhelm the crew.
/:cl:
Screenshot of it, after I added some debug code:
(Note: "RTC" in the debug text is short for "realtime clock", AKA system clock. World time is in hh:mm format.)
=> Nerfs the everliving hell out of Fungo di Artiglieria spawning

code/modules/mob/new_player/new_player.dm
Adds checks so that players won't be able to select a role they're not whitelisted for in the latejoin menu. Tested while also testing the dispatcher code.
fix: Fixed an issue where players could join as a job they weren't whitelisted for, albeit with vagabond-level access.
/:cl:
=> Fixes an issue where players could join despite being not whitelisted

code/modules/scrap/scrap.dm
This adjusts the 'failure' of looting trash piles so that it actually cuts your hands instead of your arms when a bad roll is made. It also makes it impossible to cut yourself while searching through trash piles if you are wearing a space suit.
This is good because you won't have to suspend disbelief when a pile of empty candy wrappers somehow slices your arm open through your voidsuit and does not kill you through instant depressurization of your personal atmospheric containment outfit. It also didn't make much sense that a full-body suit covering your hands... would fail to cover your hands.
:cl:
add: wearing a space suit will prevent trash piles from cutting your hands
fix: trash piles will correctly cut your hands instead of your arms when you are digging through them
/:cl:
=> tweaks trash piles to be slightly less annoying

code/modules/mob/living/carbon/human/species/station/station.dm
It interferes with eye customization 
scary frog men
:cl:
tweak: Skrells now can change eye color
/:cl:
=> Lets skrells have eye color

code/modules/mob/living/carbon/human/human.dm
Fixes the bug that causes people to have double organs.
People no longer collapse from lack of blood to fuel all their organs.
:cl:
fix: Rejuvenation-like effects (vat, cloning, aheal) no longer cause the character to have duplicate sets of organs.
/:cl:
=> Un-duplicates organs on regen

code/modules/admin/verbs/randomverbs.dm, code/modules/client/preferences.dm, code/modules/mob/gender.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/species/species.dm
In the alert menu used to select a character's gender, "plural" is now an option. It's what it says on the tin; pick this, and the character will be described with they/them pronouns. Want to make a non-binary character? Sure, do it. Want your custom species to not necessarily follow a strict male/female binary? Go ahead. Generally, this will cause the game to default to handling the character as would be the default when it comes to name generation and such.
(Note: Plural is perhaps not the _most_ accurate term, but it works and it seems to be pretty hard-baked in. My brain is not wrinkly enough to make it "_neutral_" just yet.)
(Other Note: If this sees strong use/there's demand, I can look into making sex and gender selectable separately. For now, however, biological sex seems to be …
=> Adds the option to make a gender-neutral character

code/modules/organs/internal/carrion.dm
Carrion regeneration no longer paralyzes the poor spooder
Bubg feex
:cl:
fix: Carrions are no longer forever paralyzed by regenerative stasis
/:cl:
=> Carrion regen fix

code/modules/mob/mob.dm
Makes Empty Hands a bit more forceful about it. Calls admins if it fails when it shouldn't.
Just an improvement to the Empty hands verb
There's a number of bugs that can lead to items being stuck in your hand when they shouldn't be. This should, in theory, provide a workaround, as well as giving people a single button to empty both hands quickly.
:cl:
tweak: Made Empty Hands go nuclear if the item in your hand is actually somewhere else.
admin: Empty Hands will now send a message to online admins if it fails to remove something removable from a person's hand.
/:cl:
=> Empty Hands update

code/modules/recycling/disposal.dm
Adds checks to try to ensure the item being moved to the disposal is on a turf, rather than in an object. We do this because forceMove does not trigger any UI updates, and we want to retain moving things from turfs into disposal at some things can't be put in the disposal otherwise.
This fixes a bug where players could easily get items stuck in their hand, as well as a visual bug with disposaling items out of storage containers, without clobbering existing functions.
:cl:
fix: disposal units now properly remove items from their prior location when you drag and drop the item onto the disposal.
/:cl:
=> Fix drag and drop to disposal

code/game/objects/random/ammo.dm, code/modules/clothing/spacesuits/rig/suits/combat.dm
Renames Ironhammer ammo and hardsuit to Aegis. This appears to finalize aegis compliance for strings.
Lore Compliance
:cl:
tweak: Aegis ammo and hardsuit no longer claim to belong to Ironhammer.
/:cl:
=> Aegis compliance patch

code/modules/client/preferences_savefile.dm, code/modules/core_implant/cruciform/machinery/eotp.dm
Slips in an extra check in a couple places to avoid trying to do work with null values.
While the preferences one has little to no impact, the EOTP one impacts processing because the nulls aren't removed after causing the runtime.
:cl:
fix: Fixed a couple of runtimes, including one for the Eye of the Protector.
/:cl:
=> Null runtime fixes

code/datums/ai_law_sets.dm, code/defines/procs/announce.dm, code/game/gamemodes/events/spacevine.dm
Updates drone laws to provide clearer instructions. Including how to respond to a blob/hivemind
Reduces Spacevines to a level 6 biohazard, separating them from the Blob.
Updates drone laws to provide clearer instructions. Including how to respond to a blob/hivemind
Reduces Spacevines to a level 6 biohazard, separating them from the Blob.
Gives our industrious maintenance drones clearer instructions on how to act in different situations. Also separating the Blob and Spacevines into separate alerts helps players as these two represent very different threats and require very different responses from the crew
:cl:
add: Adds a new "Level 6 Biohazard," for spacevines
del: Removed old things
tweak: replaced drone laws with a custom set courtesy of the Lore Team.
/:cl:
=> Drone laws and Spacevines

code/game/jobs/job/security.dm
Readded access_forensics_lockers to access list for Inspector job
Fix #1456 
This access is required for inspector to access gear and do job
:cl:
fix: Readded forensic access to Inspector
/:cl:
=> fix inspector ID access to allow forensics

code/__HELPERS/global_lists.dm, code/modules/client/preference_setup/augmentation/01_modifications.dm, code/modules/mob/living/carbon/brain/brain_item.dm, code/modules/organs/body_modifications.dm
They're cubes! They're intelligent! They're... positronic brains, now available in _your_ character from roundstart! 
"Humanoid positronic brain" is now an option under augmentation. Works just like an organic brain in every way other than being synthetic.
I understand this may need to be talked over.
There's been some demand for this as an option, and it doesn't provide any significant balance or gameplay changes. And hey, if we can put a posibrain into a 'borg, why can't we pop it into an empty body or humanoid chassis?
:cl:
add: "Humanoid positronic brains" as an option available under the Augmentation submenu in character creation.
/:cl:
=> adds synthetic brains

code/modules/mob/living/carbon/human/update_icons.dm
This change fixes the blend type on colorable underwear to color them properly. Light gray base sprites warrant "multiply" rather than "add" to apply color.
It fixes an oversight in a visual element of the game. Its behavior is now consistent with other colorable icons, and players now have access to the full gamut of color rather than pale tones and whitewash.
:cl:
fix: Caught the gremlins using too much bleach in the laundry. The crew's colored undies are safe now.
/:cl:
=> Edit colorable underwear to use the appropriate blend type.

code/modules/modular_computers/computers/modular_computer/interaction.dm, code/modules/modular_computers/computers/modular_computer/variables.dm, code/modules/modular_computers/computers/subtypes/dev_console.dm
Changes the amount of materials you receive from deconstructing an empty modular console frame to match the materials it took to build it.
fix #1089 
Quick and dirty bugfix to fix a teensy problem
:cl:
fix: Deconstructing a modular console will no longer give you more materials than you put into it.
/:cl:
=> Modular Console Fix

code/modules/hydroponics/spreading/spreading_growth.dm
Re-work of #404 to work with the different types of mushrooms, instead of limiting only the one. Adjusted timer to 30 seconds, so it's not quite as bad a nerf.
At some point I plan to move the rate of growth over to the config, but this is just a quick hotfix for nonfunctional code.
fix: Fix the code that originally nerfed the maintenance mushrooms' growth rate.
tweak: Doubled the rate that the original nerf allowed maintenance mushrooms to grow at. (Now 120/hour max, from 60/hour max)
/:cl:
Screenshot of test, with debug code added. Yes, they all tried to spread at the exact same time.
=> Fixes the code that nerfed the ever-living hell out of maintenance mushrooms, tweaked rate of spread

code/modules/hivemind/wires.dm
Makes the strange wires go underneath the inflatable barriers/doors for balancing sake.
Makes hivemind less trivial to deal with when deploying inflatables. Fixes #1259 
:cl:
fix: Allows hivemind's strange wires to spread underneath of the inflatable barriers. Makes it harder to deal with the hive mind.
/:cl:
=> Makes inflatables not stop the hivemind wires

code/modules/mob/mob_movement.dm
Changes the way density for the sake of ZeroG checks for pushing off, to allow for closed lockers to be push points in zeroG. Directly fixes #409
Allows places that players normally get stuck in to be points to push off of in ZeroG, therefore closing that gap. Also, fixes aforementioned Issue.
:cl:
fix: Makes closed lockers push-points for ZeroG
/:cl:
=> Lockers in ZeroG Fix

code/modules/mob/living/carbon/superior_animal/roach/roach.dm
* Roaches now only have a slim chance to spawn wearing a hat.
* Roach hats no longer glow in the dark when dropped.
*In this screenshot, only one roach is visible wearing a hat (upper left two tiles across from the bottle of liquor, wearing the brown flat cap). After a `gib()` call, another hat was visible in the pile.*
Collectible hats now have scarcity (and some value), and fixes an issue where hats would be above the lighting plane.
balance: Roaches' collectible hats now only have a 5% chance to spawn.
fix: Roaches' hats no longer glow in the dark when dropped.
/:cl:
=> Fixes and balancing changes to roaches, with regards to hats

code/game/objects/structures/window.dm
Phoron glass is now fireproof, thanks to an added `fireproof` var. 
If the fireproof var is set to true, the glass skips any fire reaction checks - this allows admins to make any glass fireproof, not just phoron.
Tested with an 8000°K hellburn in the SM chamber (peak was roughly 8500°K). No damage was taken to any of the glass during this, and the thumping noise that happens when glass takes fire damage was not observed.
balance: Phoron glass is now fireproof.
/:cl:
=> Makes phoron glass fireproof

code/modules/mob/living/silicon/robot/drone/_drone.dm, code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Adds a GPS to all drones, allowing players to track them easier.
From what I've seen of them, Blitzshell drone encounters tend to follow the route of "30 seconds of Benny Hill, 5 minutes of hiding". The goal here is to reduce the hiding and make it more Benny Hill, since trying to find someone or something hiding on the ship without a way to locate them is tedium (at best).
In order to prevent this balancing change from favouring the players too much, all drones - maintenance drones, construction drones, and Blitzshell drones - all share the same GPS prefix, `DRNE`. This favours the drone slightly if there's also maintenance drones on the ship, giving players false leads. However, attentive players will be able to tell the drones apart by looking at the number on the drone, as the GPS …
=> Adds a GPS tracker to all drones.

code/game/machinery/alarm.dm, code/modules/hivemind/machines.dm, code/modules/hivemind/mobs.dm
Some rebalancing tweaks to make Hivemind less of a round-ending event during lowpop.
For the sake of this pull request,
* The phrase "active players" means any mob that:
* Has a connected client
* Has a mind datum
* Is not deceased
* Is a human, AI, or cyborg mobtype
* Has a job assignment
* Mobs and machines now scale in health based on the number of active players. This is recalculated every tenth `Life()` and `Process()` tick for mobs and machines, respectively.
* Health and maximum health are scaled differently depending on number of active players, and have a floor of 75% and a ceiling of 100% of their default values.
* If there are fewer than 2 active players, their maximum health is a flat 25% reduction from their original values.
* If there are 3 to 10 active players, their …
=> Lowpop Hivemind balancing pass

code/controllers/subsystems/dispatcher.dm, code/controllers/subsystems/dispatcher_debug.dm, code/modules/client/preferences_spawnpoints.dm
Closes #1487 as fixed.
Adds two measures to make sure latejoin players are counted by the dispatcher: A.) players should now be tracked as they enter the game, and B.) adds periodic updates to ensure players who might get missed by A are still counted.
This has been tested on a local server by latejoining in the aft cryo and the dormitories; all three times, it added the mob to the tracking list. Performance impact of the periodic updates appear to be minimal.
In addition, should I need to, I can now pull a player tracking dump without needing to pester Nestor to grab it from the server and send it to me.
fix: Fixed a few edge cases with the dispatcher not tracking players.
/:cl:
=> Fixes dispatcher not caring about latejoin players

code/modules/core_implant/cruciform/cruciform.dm
Exactly what it says on the tin. 
Fixes - https://github.com/Eclipse-Station/NEV-Northern-Light/issues/1502
Fixes a rather critical bug
:cl:
fix: You can spawn with cruciform as non-human again
/:cl:
=> Fixes cruciforms annihilating non-humans

maps/CEVEris/_CEV_Eris.dmm, maps/CEVEris/_Eris_areas.dm
Map Changes:
- Major changes to V.I.P. Bar
- Modified layout to fit the new command restrooms, furniture changed around to make the bar feel more premium. 
- Added V.I.P. Restrooms next to V.I.P. Bar
- Minor changes to Heads of Staff Meeting Room
- Moved cigarette vendor to V.I.P. Bar
- Minor things relocated around the room to accommodate new restrooms entrance.
- Removed cell vendor.
- Added paper shredder.
- Added paperwork related utensils.
- Removed excess Soulcrypt Access Updater.
Code Changes:
- Created new area "/area/eris/command/bridgetoilet" in _Eris_areas.dm for the new room.
Adds a private restroom for Command staff to use that feels more exclusive and private than for Heads of Staff to be sharing regular restrooms with the rest of the crew. VIP bar has been transformed to …
=> Bridge update for VIP Bar and the new VIP restrooms.

code/modules/power/smes.dm, nano/templates/smes_eclipse.tmpl
Ports the 'Input Load' bar and number from older ES13 code.
This does not affect the RCon UI at all; that'll still show the input load at whatever it's set to. Another project for another day.
Quality of life change, aimed at reducing confusion why the SMES might not be outputting at maximum if it's not charged enough to output at maximum.
add: QoL: SMES units now have an 'Input Load' meter.
/:cl:
=> Ports 'Input Load' feature from ES13 SMES UI

code/game/objects/effects/spawners/corpsespawner.dm
What it says in title. They are no longer pitch black and with a pulse.
Corpses didn't look like killed mobs
:cl:
fix: fixed simplemob corpses displaying wrong
/:cl:
=> Fixes simplemob corpse spawners displaying improperly

code/modules/mob/living/carbon/superior_animal/roach/types/nitro.dm, code/modules/projectiles/projectile.dm, code/modules/projectiles/projectile/beams.dm, code/modules/projectiles/projectile/bullets.dm, code/modules/projectiles/projectile/bullettypes.dm, code/modules/projectiles/projectile/energy.dm, code/modules/projectiles/projectile/fragment.dm, code/modules/projectiles/projectile/plasma.dm, code/modules/projectiles/projectile/projectilegrenades.dm, code/modules/projectiles/projectile/special.dm, code/modules/reagents/reagent_dispenser.dm
Benzins no longer explode from blunt-force trauma. In addition, certain bullet types won't cause them to explode. In order to compensate for this, their health has been increased from 5 to 25 (on par with Jäger roaches).
Welderfuel tanks also no longer explode from being shot by certain ammo types - they will leak instead.
A roach should not explode because you went full Gordon Freeman on it.
tweak: Added a variable to projectiles to determine if it will explode welderfuel tanks or Benzin roaches.
balance: Benzin roaches no longer explode from blunt-force trauma.
balance: Benzin roaches now leak welder fuel when killed.
balance: Benzin roaches now gib when exploded. You can now detonate Benzin roaches after their death if you so desire. (Why anyone would WANT to do …
=> Balancing tweaks to Benzin roaches

code/game/objects/effects/decals/Cleanable/fuel.dm, code/modules/mob/living/carbon/superior_animal/roach/types/nitro.dm
Fixes welding fuel behaviour when it spreads across an open space turf. Previously, it would spread to the open space turf, then fall. Now, it calculates where it would land and spreads there instead of directly on the open space turf.
Fixes an edge case where Benzins lit on fire wouldn't explode. Now, they're a bootleg grenade, with a timer between 3 and 15 seconds.
Fixes an edge case where Benzins could leak welding fuel more than once under certain circumstances.
Closes #1545 as fixed.
Fixes some bugs, and fixes some bugs.
tweak: Partially refactored how welding fuel spreads, to account for Z-level travel.
fix: Fixed an issue where welding fuel would create a stack of puddles atop each other if they fell a Z-level.
fix: Fixed an edge case where a Benzin lit on fire …
=> Fixes welding fuel behaviour with regards to Z-levels

cev_eris.dme, code/game/gamemodes/events/hidden_events/spider_nest.dm
Adds a new hidden event, the "Spider Nest," which will spawn a spider nest somewhere on the ship.
Currently the Carrion is discouraged from using its "spider nest" ability as the moment another player discovers it, they are instantly and provably certain that a Carrions is aboard. This event will temper that paranoia, and give the Carrion a means of plausible deniability.
:cl:
add: Added Spider Nest event
/:cl:
=> Spider Nest

code/controllers/subsystems/economy.dm, code/game/jobs/department.dm, code/game/jobs/job/security.dm, code/game/machinery/cryopod.dm, code/modules/modular_computers/file_system/reports/crew_record.dm, code/modules/shield_generators/modes.dm, maps/CEVEris/_CEV_Eris.dmm
fixes #1561 :
- Adds accounts database terminal to personnel office
- Adds check in payroll for crew status, only crew set to "active" in crew records will get paid
- <s>I attempted to  write code to automatically update the status of a mob in "Crew Records" to "Cryostasis" when their mob is despawned in cryopod.dm, but was unable to get it working. Currently workaround solution is that an active head will need to set crew who've gone to cryo, died, or otherwise should not be paid, to a status other than Active.</s> Thanks to EvilJackCarver for figuring out the automation problem!
Adds two new statuses, "Cryostasis" and "Off Duty" for heads to more finely adjust activity.
- "Cryostasis" is for crew who have left the round
- "Off Duty" is for crew on a leave of some kind, whether voluntary …
=> Stonks and Shields

code/controllers/subsystems/dispatcher.dm
Comments out redundant periodic updates to the player-tracking part of the dispatcher.
The periodic updates were originally intended as a fallback method to ensure players who spawned in the dorms were added to the tracking. Right now, it's just redundant code that occasionally adds in bluespace technicians and admeme spawns to the tracking lists whether or not the admemes wanted them on the tracking lists, which isn't desirable.
del: The NTDAD player tracking system will no longer periodically add everyone who isn't on the list to the lists.
fix: Fixes an issue where bluespace technicians would show up in the NTDAD player tracking system.
/:cl:
=> Comments out periodic player-tracking updates.

code/game/objects/items/weapons/tools/mods/mod_types.dm
https://github.com/discordia-space/CEV-Eris/pull/6860
hydraulics have an intended effect
:cl:
fix: Hydraulic circuits now have their intended effect, again, instead of the plasma coating's effect. (Earlyported from upstream.)
/:cl:
=> upstream earlyport 6860 - hydraulics fix

maps/CEVEris/_CEV_Erida.dmm
Fixes the engine waste line on the Erida being not connected to the hot loop. Fixes the shield generator not being connected to the power grid.
Engine delams are bad, mmkaaaaaaaay?
fix: Engine waste line is now connected to the filters.
fix: The shield generator is now connected to the Engineering electrical sub-grid.
/:cl:
=> Fixes engine wasting line on the Erida.

maps/CEVEris/_CEV_Erida.dmm
puts a SMES coil box next to the SMESes
power grid funnies
:cl:
add: The CEV Erida now has a SMES coil box, like the Eris did. It's just tucked into a corner of the SMES room.
/:cl:
=> CEV Erida - SMES Parts Box

code/game/gamemodes/events/weather/rad_storm.dm
For some odd reason, the weather event for the rad storm uses a different check than the actual radiation check does. This does not fix that. This adds the "erida" maints area (and therefore subtypes) to the list it checks, protecting maintenance from the purely visual effects of the weather event. Please someone fix this properly some day so I don't have to learn how to do it myself.
Misleading visuals.
:cl:
fix: Maintenance on the Erida will no longer falsely appear to be irradiated during radiation events.
/:cl:
=> Fix rad storm weather event visuals

maps/CEVEris/_CEV_Erida.dmm
Firstly, I swear I have no idea how to make strongdmm NOT clean default vars. So this has a lot of "bloat". Secondly, this adds cycle buttons outside the junk tractor beam airlock on either side, allowing yada yada you don't have to hack it open roundstart, you don't have to hack it open when someone leaves through it. Additionally, it moves the JTB console around to the correct location, since for some MAD reason it's coded to require the "interference dampeners" in VERY specific relative locations to its RIGHT. It quite simply does not work in any other location.
I tested it, it all works, hurrah.
Uh... the airlock works right? The JTB console works? Sounds good to me.
:cl:
fix: JTB airlock has cycle buttons, and the console has been moved to its appropriate location.
/:cl:
=> Junk tractor beam console, airlock, strongdmm cleaning default vars.

maps/CEVEris/_CEV_Erida.dmm
I've added two extra spider cluster spawns aswell as decreasing the size of the windows in the room to prevent mice-spawn from distracting the entire nest as easily. 
Before: 
After: 
Will provide a more difficult challenge for the loot inside the room, currently you get way too good loot for a challenge that is negligible due to lack of numbers and/or the presence of mice in the adjacent maint tunnel
:cl:
add: Added new spider cluster spawns
tweak: tweaked the maint window size
/:cl:
=> More spiders in dungeon / Less window

maps/CEVEris/_CEV_Erida.dmm
This has been annoying me forever. Swaps it off of space to the actual maintenance area, probably has a dozen other ramifications. Edit: I did more, and hopefully fixed that AGRAVATING goddamn holomap by the mining shuttle that keeps slurping me into it every time I go by.
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
:cl:
fix: Removed space area from maintenance, ridding us of a maintenance shield.
/:cl:
=> Removes errant space tile in maints

code/modules/admin/view_variables/helpers.dm, code/modules/admin/view_variables/topic.dm
Adds in administrative tools to fix players' markings, e.g. if they get cloned. 
The reason this is not automatic is to avoid a potential edge case where someone who is missing a limb during or after cloning (e.g. their head was gone, they got thrown in the basin, their head is no longer gone) who then has their markings regenerated could then have an errant marking visible on a missing limb.
Currently, if I want to fix someone's markings after they get cloned, I either have to call a proc that does a lot more than just copies over their markings, or I have to raise the metaphorical mollyguard on the SDQL console and manually copy their sprite markings over from their `dna` datums to their mob variables.
Also adds a direct button to call the proc that does a lot more than just copy over …
=> Adds options to regenerate player icons to VV dropdown menu

maps/CEVEris/_CEV_Erida.dmm
Fixes #1647 
Basically, there just weren't disposals underneath the spots with the shutters. Tada, now there are.
:cl:
fix: Bar disposals will no longer dump trash into the back room.
/:cl:
=> Fixes bar disposals

code/modules/shield_generators/shield_generator.dm, maps/CEVEris/_CEV_Erida.dmm
Adds an overheating mechanic to the shields.
This update is part of a balancing pass to make shields less set-and-forget. 
Shields will now generate heat based on the following factors:
* Ambient temperature
* Total power draw
* Power required to maintain the shields' integrity.
The shields are air-cooled, meaning they take air in from the environment, heat it based on the power draw, and exhaust it back into the environment (much like an air-cooled computer tower). At lower ambient temperatures, the power draw required to maintain the shields is higher, as the shield generator is not at operating temperature; the lower the temperature, the higher the required power draw needed to sustain the shields. This is capped at a maximum of a 4× multiplier and a floor of a 1× multiplier.
If the …
=> Shield overheat mechanics

code/game/objects/items/weapons/tools/multitool.dm
Title is a meme but the point is, multitools can pulse lockers to open them, it'd be good to make it visible that they can do such
Get players interacting with a not-entirely-known feature
:cl:
tweak: Multitools now show in their examine text that they can hack open lockers
/:cl:
=> Adds ", lockers," to the multitool description

code/modules/mob/living/simple_animal/borer/borer.dm, code/modules/mob/living/simple_animal/borer/borer_powers.dm
A series of modifications to borers. Key changes include:
- Permitted borers to use telepathy while outside and inside of a host.
- Halving both the chemical cost and reagents produced by the “secrete chemicals” option, to 25 and 5 respectively, to reduce issues with overdosing.
- Rebalanced upgrade costs from 20, 40, 80, 160, 320 to 20, 40, 80, 140, 220 to reduce issues with the number of times borers need to reproduce to level up.
- Added a number of new chemicals, including mood stabilisers to counter common mood issues (Citalopram and paroxetine) at levels one and three respectively, nutriment for hunger at level one, dylovene to address the lack of toxin healing chemicals at level three, ethylredoxrazine (alcohol counter) at level two, and zombie powder at level four.
Psychic whisper …
=> Borer modifications

code/game/jobs/access_datum.dm, code/game/jobs/job/captain.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/guild.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/machinery/computer/medical.dm, code/game/machinery/computer/robot.dm, code/modules/mob/living/silicon/robot/drone/drone_console.dm, code/modules/modular_computers/file_system/programs/engineering/atmos_control.dm, code/modules/modular_computers/file_system/programs/engineering/power_monitor.dm, code/modules/modular_computers/file_system/programs/engineering/rcon_console.dm, code/modules/modular_computers/file_system/programs/engineering/shield_control.dm, code/modules/modular_computers/file_system/programs/engineering/supermatter_monitor.dm, code/modules/modular_computers/file_system/programs/generic/camera.dm, code/modules/modular_computers/file_system/programs/generic/records.dm, code/modules/modular_computers/file_system/programs/medical/chem_catalog.dm, code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm, code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm, code/modules/modular_computers/file_system/programs/security/forceauthorization.dm, code/modules/modular_computers/file_system/reports/crew_record.dm, code/modules/reagents/machinery/chem_dispenser.dm, code/modules/research/server.dm, maps/CEVEris/datums/reports.dm
- creates new access levels specifically for department consoles
- changes access requirements of consoles / programs to new console accesses
- alters Boff access to remove department accesses they don't need and grants them console access. Fixes #1495 
These changes allow me to finally remove the scuffed access from Bridge Officers, as they'll no longer need to have odd access across the ship. This also makes several new access levels to allow heads more granularity when assigning access to departments, as consoles / programs are their own access level now, rather than sharing door / equipment access.
:cl:
fix: Fixed Bridge Officer access. Consoles / programs now have their own access levels by department.
/:cl:
=> Finally Fixing Bridge Officer Access

code/modules/shield_generators/shield_generator.dm
Fixes an issue where shield generator's HTCO won't trigger a second time, and some miscellaneous tweaks.
:cl:
fix: Shield generator high-temperature cutoff now resets properly.
tweak: Shield generator overheat alarm now additionally broadcasts to the command channel.
tweak: Shield generator emergency stop sets the input cap to 1 kW instead of 1 W.
/:cl:
=> Shield generator overheat fix

cev_eris.dme, code/datums/outfits/jobs/church.dm, code/datums/outfits/jobs/command.dm, code/datums/outfits/jobs/engineering.dm, code/datums/outfits/jobs/guild.dm, code/datums/outfits/jobs/medical.dm, code/datums/outfits/jobs/science.dm, code/datums/perks/fate.dm, code/game/jobs/job/security.dm, code/game/objects/items/weapons/manuals.dm, code/game/objects/structures/crates_lockers/closets/job_closets.dm, code/modules/modular_computers/file_system/programs/engineering/shield_control.dm, code/modules/reagents/metabolism.dm, maps/CEVEris/_CEV_Erida.dmm, zzz_modular_eclipse/code/game/objects/items/weapons/manuals.dm
- Removes Engi-vend from public hall
- Heads of Staff now get the weapons our changelog says they should have. Fix #1652 
- Fixed Wiki Manuals, All manuals now point to the correct pages. Fix #1626
- added a new wiki manual for The Agreement and a Guide to Mekhane, and I also corrected some of the sprites in the others
- slightly adjusted locations of intercoms in dorms and cryostorage to fix #291
- Fixed Alcoholic perk only selecting Ethanol and nothing else.
- Fixed missing access for security roles to use their consoles.
1. The Engi-Vend is a specific vending machine that is meant to store engineering tools, and be used exclusively by engineers, which is why it dispenses for free. There is already one in the Engineering Break Room, and so two is excessive.
2. Heads of Staff were …
=> Bug-fixes and Minor Tweaks

code/game/machinery/atmoalter/scrubber.dm
Replaces cells in portable scrubbers  with atom cells because I want to fix them quickly and cannot be arsed to determine whether or not they're supposed to use power cells or not at this moment.
fix #1649 
Right now there is no way to replace the cells in portable scrubbers, making them non-functional once their limited charge runs out. Comments in the code imply that they shouldn't even be using cells, but while I determine which way we're supposed to go, this will make them functional.
:cl:
fix: gave portable scrubbers self-charging cells
/:cl:
=> Scubber Fix

code/datums/mob_stats.dm, code/modules/virus2/disease2.dm
Reverts Eclipse-Station/NEV-Northern-Light#1685
The PR made all players spawn with no stats.
=> Revert "Stat limiter"

code/controllers/subsystems/processing/mobs.dm
Basic warnings, so we can catch it before it becomes a huge problem.
:cl:
add: Adds a warning if the number of mobs gets too insane.
/:cl:
=> Admins (and players, if no admins are on) are now warned if the mobs subsystem has too much to handle.

code/modules/core_implant/cruciform/modules.dm
- Added the resurrection litany to the acolyte
Adds the resurrection litany to the acolytes so they may attach the cruciforms on newly-resurrected bodies. Fixes #1693 
It does not make sense that Acolytes can induct new people, but not resurrect existing ones. This way, if a priest is not on but a member of the church is, you may be respawned.
:cl:
add: Resurrection Litany to Acolytes 
/:cl:
=> Changelog:

maps/CEVEris/_CEV_Erida.dmm
This update makes all the changes necessary to ensure that a basic power setup is automatically online at round-start. The following screenshots are taken on a fresh round with no player input into the setup:
- All 8 phoron canisters (and 1 Nitrogen for the waste cooling) are on their correct ports.
- All necessary pumps and filters are online and set to the correct settings
- Emitter is on by default
- Substation SMES's have their inputs turned on (values have not been touched)
- The Engineering substation has been bypassed to prevent the gravity generator going offline.(*)
(*)- This jury-rigged bypass does connect the Engineering Subgrid directly to the SM, which I know has been something that has caused repeated, heated arguments among engineer players. I wouldn't have done this except …
=> Automated Power Setup

code/modules/clothing/clothing.dm, code/modules/clothing/spacesuits/rig/modules/modules.dm, code/modules/clothing/spacesuits/rig/rig.dm, code/modules/mob/living/living.dm
closes #455
Fixes oddies that are put in a shoe or vest not being detectable via the inspiration system
No longer does shoving a oddity into a normal interaction with a normal system punish you for not knowing that clothing pier to this change are scanned for "are you holding something?"
This also has been updated for rig storage units.
Disclamer this was tested on Soj with a same pr being made, as for testing on soj i had slamed a knife in a bst boot and then drank beer and leveled up using it well having a puff jacket with a coin as a "does this work for everything"
Put a coin oddity in a rig in hand, then a knife in a storage unit in back rig then a 2nd coin in a second rig in hand, leveled up saw all 3 in the menu and working.
:cl: Trilby
fix: oddities put in clothing and rigs are now …
=> Fixes oddies not being detected in clothing

code/modules/core_implant/cruciform/rituals/construction.dm
[Ports](https://github.com/sojourn-13/sojourn-station/pull/5407), this should fix being unable to build proper bioreactors
Churchies should be able to do what they are given the power to do without bugs
closes #1437
Tested on soj, not on current NEV, requesting this be test merged.
:cl: benj8560
fix: fixes bioreactors blueprints to allow crafting of a bioreactor from scratch
/:cl:
=> bioreactor buildable

code/game/machinery/autolathe/autolathe.dm
closes #1774
Fixes douping mater via directly adding matter into printers
V_V Lament, Mourn, and Despair V_V
Ran a test server, clicked direct recycle with a stack of 5 plasteel then saw it add 5 rather 25. Added a welder, got correct matter and chems, then wires and also got correct matter
:cl:
fix: fixes autolathe matter douping 
/:cl:
=> Fixes autolathen mater douping

code/game/machinery/adv_med.dm
Closes #1812 
Fixes most organs not properly showing up on a scanner unless rejected
This matches upstream, so not a edit from here
Fixes a small issue when upstream merge happend
:cl:
fix: advanced scanners not giving proper organ reading
/:cl:
=> untabbed adv_med

code/controllers/configuration_eclipse.dm, code/modules/shield_generators/shield_generator.dm, config/example/config_eclipse.txt
Adds config options for the shield generator's heat generation mechanic. These include...
- A master disable switch
- A flat, adjustable multiplier
these are `DISABLE_SHIELDGEN_HEAT_GENERATION` and `SHIELDGEN_HEAT_MULTIPLIER`, respectively
affects #1806 but does not properly fix it
stopgap fix until we can work in mapping changes
Runtime tested. Shield generator disable and heat multipliers appear to work as intended.
:cl: eviljackcarver
add: added config options for the shield generator's heat mechanic
config: eclipse config updated to version 10
/:cl:
---
~~it literally took longer to get tortoisegit working properly than it did to code and test.~~
=> Adds configuration options for the shield generator

maps/CEVEris/_CEV_Erida.dmm
- Adds in a control room and cooling systems for the shield generator.
- Adds in a quick-and-dirty pass with the Semiotic Standard signage, for all commercial trans-stellar utility lifter and heavy element transport spacecraft.
Closes #1806 as fixed.
Shields not overheating is a good thing, yes?
The shield generator room changes were tested in-engine to verify it would be enough to cool the system down while the generator was under active load.
Outside of that, all other changes have only been compiler tested.
fix: shield generator room now has a proper cooling system installed.
add: Quick-and-dirty pass with Semiotic Standard signage around the ship.
/:cl:
=> Shield generator room update, basic semiotic signage pass

code/_compile_options.dm
Adds a compiler warning for when a player attempts to compile things for Byond version 515. For more information, see #1809.
**This PR contains no player-visible changes.**
Less confusion for when people try to help out is always good.
Tested on 515.1643, compiler warning appeared before the errors did (though if TGUI is compiled, it gets slightly lost.)
Tested on 514.1589, compiler warning was not present.
:cl:
server: Minor tweaks to compiler settings. No player-visible changes.
/:cl:
=> Updates _compiler_options.dm to include a warning when you try to compile on 515.

tools/changelog/generate_cl.py
The subroutine it was trying to call is deprecated and removed, and thus throws errors. 
```py
Traceback (most recent call last):
File "/home/runner/work/NEV-Northern-Light/NEV-Northern-Light/tools/changelog/generate_cl.py", line 71, in <module>
tags = yaml.safe_load(file)
File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/ruamel/yaml/main.py", line 1108, in safe_load
error_deprecation('safe_load', 'load', arg="typ='safe', pure=True")
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/ruamel/yaml/main.py", line 1042, in error_deprecation
raise AttributeError(s, name=None)
AttributeError: 
"safe_load()" has been removed, use
yaml = YAML(typ='safe', pure=True)
yaml.load(...) …
```
=> Changelog compiler tweaks

.github/workflows/ci_suite.yml, .github/workflows/compile_changelogs.yml, .github/workflows/conflicts.yml, .github/workflows/generate_documentation.yml, .github/workflows/show_screenshot_test_results.yml
Ubuntu 20.04 LTS has been removed from service by GitHub. This updates us to use `ubuntu-latest` on all workflows (including the one which currently uses 22.04) for futureproofing purposes. 
(If we need to fall back to a specific version later, it's easy enough to do so.)
So we don't lose more workflows because of GitHub deprecating operating systems
This is a change to a GitHub workflow, and thus cannot be tested without merging.
Changelog intentionally left blank.
=> Updates workflows for futureproofing
