Eclipse-Station/NEV-Northern-Light

tools/merge-upstream-pull-request.sh
<details>
<summary>Expand</summary>
</details>
<details>
<summary>Expand</summary>
</details>
=> Upstream bot 

code/game/jobs/job/civilian.dm
botanist man no have access
me fix
made as a result of https://github.com/Eclipse-Station/NEV-Northern-Light/issues/40
=> fixes botanist access

code/game/jobs/job/civilian.dm, code/modules/tips_and_tricks/gameplay.dm, code/modules/tips_and_tricks/jobs.dm, code/modules/tips_and_tricks/mobs.dm
Fixes some typos, makes other things more clear, removes echoes of Eris lore (lol technomancers), also added a few hints in.
I was also going to add a Nuclear Throne joke in there but didn't.
=> updates tricks & tricks messages

tools/changelog/generate_cl.py
:cl:
fix: fixed angry changelog generator after it gets no changelog
/:cl:
=> Fixes changelog failing

.github/workflows/compile_changelogs.yml
:cl:
tweak: Changed changelog generator cooldown
/:cl:
=> Make changelog compiler run every hour, instead of every 15 minutes

.github/workflows/compile_changelogs.yml
:cl:
fix: changes repo to the proper one
/:cl:
=> Small changelog autocompiler fix

tools/changelog/generate_cl.py
=> Fixes CL generator

code/game/jobs/job/civilian.dm
=> mi fix janitour acciess

code/datums/craft/recipes/weapon.dm
noticed you could craft telespears but not normal spears
glass spears already exist
did this
lol
=> allows the crafting of glass spears

code/datums/craft/recipes/weapon.dm
:cl:
fix: restores master branch
/:cl:
=> removes a commentary from inside of a list

code/modules/biomatter_manipulation/biogenerator.dm, code/modules/biomatter_manipulation/bioreactor/bioreactor.dm, code/modules/biomatter_manipulation/bioreactor/biotank.dm, code/modules/biomatter_manipulation/bioreactor/console.dm, code/modules/biomatter_manipulation/bioreactor/platform.dm, nano/templates/bioreactor.tmpl, nano/templates/nt_biogen.tmpl
Adds UI elements to the biogenerator and bioreactor, removes neotheo requirement for usage by request of Nestor.
I also redid some of the grammar, because it was fucking awful.
I assume because NeoTheo is going away?
:cl:
add: UI elements for bioreactor and biogenerator
tweak: Grammar fixes
/:cl:
=> Biogenerator / Bioreactor UI additions and improvements

maps/submaps/deepmaint_rooms/normal/normal_rooms.dm, maps/submaps/deepmaint_rooms/normal/oldchurch.dmm, maps/submaps/deepmaint_rooms/normal/oopsitsphoron.dmm
**CHANGELOG:**
adds two new rooms to deep maints, both are normal rooms.
room 1: OOPS!!! ALL PHORON!!!
literally just an atmos chamber that has a small amount of phoron mixed w/ o2. contains tempting loot but is pretty hazardous if you're a moron
tested, will not set all of deepmaint on fire
room 2: old church
old NT church. relatively 'safe' area, lacks roach spawns and filth to emphasize how church-y it is. little loot.
=> adds 2 deepmaint rooms aaaaaaaa

code/datums/autolathe/biomatter.dm, code/datums/contract.dm, code/datums/uplink/badassery.dm, code/game/antagonist/station/marshal.dm, code/game/objects/items/devices/holowarrant.dm, code/game/objects/items/devices/propaganda_chip.dm, code/game/objects/items/weapons/storage/belt.dm, code/game/objects/items/weapons/tools/knives.dm, code/modules/clothing/under/jobs/civilian.dm, code/modules/projectiles/guns/energy/plasma.dm, code/modules/projectiles/guns/mods/mods.dm, code/modules/research/designs/weapon.dm, maps/CEVEris/datums/reports.dm
Removed more Eris mentions. (Ironhammer and Moebius, a few NeoTheology mentions) and added a few lines to the propaganda chip.
We're not Eris.
:cl:
add: New Propaganda Chip Lines.
tweak: Fixed mentions of Ironhammer, Moebius, NeoTheology and a mention of the corporate Wars.
/:cl:
=> Removed more Eris Mentions

maps/submaps/deepmaint_rooms/normal/normal_rooms.dm, maps/submaps/deepmaint_rooms/normal/oopsitsbeartraps.dmm, maps/submaps/deepmaint_rooms/normal/oopsitsphoron.dmm
fixes oopsitsphoron.dmm from not having a door, also lowered actual amount of phoron due to my own concern of it being excessive still.
adds oopsitsbeartraps.dmm
this is good for the game because doors are good. also it adds a deepmaint room. said deepmaint room is a small shelter/hut that is full of garbage and beartraps. 
:cl:
add: added oopsitsbeartraps.dmm
fix: fixed oopsitsphoron.dmm
/:cl:
http://puu.sh/G2rw6/d1f80a6657.jpg
http://puu.sh/G2rvg/4d39532f96.jpg
im gonna cry
=> adds another deepmaint room, fixes phoron deepmaint map

code/datums/perks/job.dm, code/datums/setup_option/backgrounds/fate.dm, code/datums/setup_option/backgrounds/origin.dm
changes backgrounds to not be ultra specific to eris lore
also changes some adding 35 stats total lol
changes fate descriptions, makes some more clear & corrects typos
clarity good, eris lore man not in eclipse
:cl:
tweak: changed background descriptions
balance: changed background stats
tweak: changed fate descriptions
:cl:
=> changes backgrounds to be more generic, changes fate descriptions

code/datums/setup_option/backgrounds/origin.dm
Terminates a line of text preventing code compilation.
PR format so I can check for other code issues while I'm here.
=> Terminates text preventing code compile

cev_eris.dme, code/modules/admin/verbs/randomverbs_eclipse.dm
Ports Virgo's implementation of the 'spawn character' verb. I had to make some tweaks for it to work with Eris code, so it's not 100% identical to Virgo's, but it's reasonably close.
https://www.youtube.com/watch?v=gwc9P07QXlc
Closes #286
admin: Ported Virgo's 'spawn character' verb. It's under 'special verbs' tab. It's not 1:1 because I've had to rework it a bit to work with Eris code, but it's close enough that it should work for events.
/:cl:
=> Ports Virgo's 'spawn character' verb

code/game/objects/structures/crates_lockers/closets/secure/medical.dm, maps/CEVEris/_CEV_Eris.dmm
* Tweaks request consoles
* Tweaks pattern of shield diffusers in the Junk Beacon "room" (#400)
* Adds missing fire alarms to atmospherics, engine bay, chemistry, and anomalous materials lab
tweak: Tweaked request consoles a bit on the map, and added a couple more (mostly in medical)
tweak: Tweaked pattern of shield diffusers in the Junk Beacon room
add: Added missing fire alarms to some departments
add: Adds a second vial pouch to chemistry lockers, by Saffron's request
/:cl:
=> NTDAD map changes

code/__HELPERS/global_lists.dm, code/modules/client/preference_setup/augmentation/01_modifications.dm, code/modules/organs/body_modifications.dm
:cl:
fix: Fixes church people spawning with normal limbs instead of robolimbs
fix: Fixes people being able to attach meat limbs to robolimbs (meat feet to robotic legs or meat arms to a robotic torso)
/:cl:
=> Hotfix church limbs

code/datums/setup_option/core_implants.dm, code/game/objects/items/complicator.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/core_implant/cruciform/machinery/vat.dm, code/modules/core_implant/cruciform/modules.dm, code/modules/mob/living/carbon/human/death.dm, code/modules/mob/living/carbon/human/human_defines.dm
:cl:
add: Adds genetic stabilization
fix: Cruciforms now properly carry ckeys
add: Cruciforms can now be uploaded into the vat
add: Adds un-husking to the vat
tweak: The vat has been buffed as well as genetic instability toned down becausse jesus christ those mutants.
/:cl:
=> Yet Another Vat Update 

cev_eris.dme, code/__HELPERS/logging.dm, code/modules/client/preference_setup/global/preferences.dm, code/modules/mob/say_subtle.dm
Adds the subtle verb with the accordance for new rules
Ghosts can't see it unless they toggle it on
Horni. 
:cl:
add: Added subtle verb for all you subtlety needs. We all know what it's for. Don't pretend that you don't.
/:cl:
=> A little subtlety never hurt nobody 

code/__HELPERS/antag.dm, code/game/gamemodes/roleset/roleset.dm, code/game/objects/items/devices/last_shelter.dm
Exactly what it says on the tin
Those options were grammatically incorrect, and honestly, kinda rude
:cl:
tweak: removes coarse language from antag popups
tweak: restores old Last Shelter functionality
/:cl:
=> Removes coarse language and restores old Last Shelter performance

merge-downstream-pull-request.sh
for the downstream bot
free code yay
:cl:
server: replaces dead downstream with a newer one 
/:cl:
=> friendship ended with syzygy now occulus is our downstream

maps/CEVEris/_CEV_Eris.dmm
- Fixed church map
- Added scrubbers to the mining hulk
:cl:
add: Added scrubbers to the mining hulk
fix: Fixed church map
/:cl:
=> Map Changes

code/game/antagonist/alien/borer.dm, code/game/antagonist/antagonist.dm, code/game/antagonist/outer/blitzshell/blitzshell.dm, code/game/antagonist/outer/mercenary/merc_faction.dm, code/game/antagonist/station/changeling.dm, code/game/antagonist/station/inquisitor.dm, code/game/antagonist/station/marshal.dm, code/game/antagonist/station/revolutionary/excel_faction.dm
Fixed the antag blurbs to more properly fit with the lore. Changed to match the Lore Team's documents. 
Makes the Antagonists fit in better with the game's lore by changing their welcome text!
:cl:
fix: Fixed the welcome text for _**almost all**_ antags. 
/:cl:
=> Changed Welcome Blurbs

cev_eris.dme, code/datums/security_state.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/paperwork/stamps.dm, code/modules/reagents/reagents/food-Drinks.dm, code/modules/reagents/recipes.dm
-Added in a Gunnery Sergeant's stamp for the GS's use.
--Put the stamp in the locker
-Changed out the armor in the Sergeant's Locker with the webbed armor 
-Added a Whiskey on the Rocks. Because why not. 
The Whiskey On the Rocks is a usual, simple beverage used in bars across the world. No reason to not have it.
The Gunnery Sergeant needs a stamp for approving paperwork, because I am sadistic and want people to do more paperwork. (And the lore team made me.)
Webbed armor so the Sergeant has POCKETS. That's right baby, POCKETS!
:cl:
add: Whiskey on the Rocks (one part Whiskey, two parts ice), Gunnery Sergeant's Stamp (Placed in the Locker)
tweak: Replaced the Armor in the Gunnery Sergeant's Locker with Webbed Armor, as per suggestion, Tweaked the security announcements for Red and Blue to …
=> Security Levels and Item Changes 

code/modules/reagents/recipes.dm
Fixes Whiskey values
Whiskey no longer gives you too much of a drank
:cl:
tweak: Changed Whiskey from 1:2 for 4 to 1:2 for 3
/:cl:
=> Whiskey Patch

code/datums/autolathe/biomatter.dm, code/datums/autolathe/devices.dm, code/game/gamemodes/scores.dm, code/game/jobs/department.dm, code/game/objects/effects/misc.dm, code/game/objects/items/weapons/design_disks/NeoTheology.dm, code/game/objects/items/weapons/grenades/chem_grenade.dm, code/game/objects/items/weapons/storage/boxes.dm, code/modules/core_implant/cruciform/machinery/cruciformforge.dm, code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/priest.dm, code/modules/projectiles/guns/energy/nt_svalinn.dm, code/modules/stashes/stash_types/valueables.dm
Now with 100% less borked code!
Replaced references to Neotheology in various descriptions, no mechanical changes.
The Heretical texts of Neotheology must be PURGED from our divine codebase!
:cl:
code: Replaced references to Neotheology with Mekhane or NanoTrasen as appropriate (Laser Weapons now should all be NT branded, Melee Weapons and Church special grenades are labelled Mekhane)
/:cl:
=> Eris Lore Purge 2 - Electric Boogaloo

maps/CEVEris/_map_data_Eris.dm
Un-docks the ship
The dock storyline has reached the point of un-docking
:cl:
add: The ship back off the dock!
/:cl:
=> Un-docks the ship

code/game/antagonist/station/inquisitor.dm, code/game/antagonist/station/marshal.dm
-Changed Bounty Hunter and Inquisitor Escape objective to Survive
-Tweaked wording on inquisitor welcome text to better fit the lore.
-renamed Marshal to Bounty Hunter
escape can only be completed by abandoning the ship, something we do not wish to encourage.
:cl:
tweak: Changed Bounty Hunter and Inquisitor Escape objective to Survive
spellcheck: Fixed Inquisitor welcome text
spellcheck: renamed Marshal to Bounty Hunter
/:cl:
=> Crew Sided Traitor tweaks

code/modules/mob/living/carbon/superior_animal/roach/life.dm, code/modules/mob/living/carbon/superior_animal/roach/riding.dm, code/modules/mob/living/carbon/superior_animal/roach/roach.dm, code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm, code/modules/mob/living/carbon/superior_animal/roach/types/nitro.dm, config/custom_items.txt, zzz_modular_eclipse/code/modules/custom_items/itemlist.dm
Apparently, explosion and death code for superior animals is fucked
No more lag spikes
:cl:
fix: Fixes benzines this time for real
/:cl:
=> Fixes Benzines chain exploding for real

code/__DEFINES/jobs.dm, code/datums/autolathe/guns.dm, code/game/jobs/job/church.dm, code/game/jobs/job/security.dm
Changes to the Access Modification Program:
Fixed church jobs, they now show up under the correct names and are assignable
Removes dead jobs like "Lazarus Representative," "Brig Physician," and "Supply Manager"
Fixed Job Access:
Fixed security access, all sec roles have access to the permabrig and EVA now
Fixed Church access, previously only the preacher actually got access to the church  through their ID, all other church positions required the access from their cruciform, this has created problems when  someone was revived, sometimes it would wipe the access, now it is stored on the ID as well. (This also means that the church can now use guest pass terminals).
Also fixed the autolathe entry for the Drozd to show the correct ammo type.
Makes the Access modification computer more usable, …
=> Access Fix

code/modules/client/preference_setup/loadout/lists/accessories.dm, code/modules/client/preference_setup/loadout/lists/eyegear.dm, code/modules/client/preference_setup/loadout/lists/footwear.dm, code/modules/client/preference_setup/loadout/lists/gloves.dm, code/modules/client/preference_setup/loadout/lists/headwear.dm, code/modules/client/preference_setup/loadout/lists/misc.dm, code/modules/client/preference_setup/loadout/lists/suits.dm, code/modules/client/preference_setup/loadout/lists/uniforms.dm
Greatly expands the selection available from the loadout screen.
This is intended to be just the first part of some work I intend to do with the sprites on our codebase, as there are literally hundreds of unused and unloved sprites, and while many of them might not fit our server thematically, there are many that I can absolutely find uses for.
Roleplayers love customization in all things, and this gives people a LOT more options. Besides that, many of the items added were locked away from the players with no way to access them, and what's the point of even having outfits that people can't use if they  so choose?
:cl:
add: Added dozens of new items to the loadout menu!
tweak: altered the restrictions on many loadout items that didn't make sense, And fixed a few that were broken.
/:cl:
=> Loadout Overhaul

code/modules/clothing/masks/miscellaneous.dm
Exactly what's on the tin. Thanks to Rikkan to bringing the problem file to our attention.
Bugfeex
:cl:
fix: bandanas now display when worn on the head instead of face
/:cl:
=> Fixes bandanas

code/game/antagonist/antagonist.dm, code/game/objects/items/stacks/medical.dm, code/modules/clothing/accessories/badges.dm, code/modules/reagents/reagent_containers/food/cans.dm
Corrects all current errors submitted on the Lore Suggestion Form
FIX ALL THE THINGS!
:cl:
spellcheck: fixed a typo in the Syndicate Operative welcome text
spellcheck: Mekhane First aid kit now has Mekhane components in it
spellcheck: Aegis holobadges no longer say Ironhammer or Cobalt
spellcheck: Thirteen Loko no longer references the MBO
/:cl:
=> Lore Suggbox Fixes

config/custom_items.txt
Whoops.
Fix
:cl:
fix: whoops fixed Gman222's gift for Selakitteh
/:cl:
=> Fixes a wrong ckey in custom items

code/modules/core_implant/cruciform/rituals/construction.dm, code/modules/core_implant/cruciform/rituals/crusader.dm, code/modules/core_implant/cruciform/rituals/inquisitor.dm
Changes all of the litanies that referred explicitly in masculine pronouns to use neutral instead. Fixes #1099 
Makes litanies work with every character logically instead of simply filling in "he". In the future, it will be changed to pull the caller's registered pronouns.
:cl:
fix: Litanies now use neutral pronouns instead of he, him, and his for everything. 
/:cl:
=> Litany pronoun replace

code/modules/modular_computers/file_system/programs/medical/chem_catalog.dm
…s a temporary placeholder
Changes the name of nIRC to LIRC to reflect the fact it is owned by Lazarus
Slight program name and description adjustments to make it fit with the lore better.
:cl:
fix: Changes  nIRC to LIRC, and changes the description as well.
/:cl:
=> Updates nIRC to LIRC

code/game/machinery/autolathe/autolathe.dm
Fixes #1090 by disallowing users from putting in any amount of an item less than one into any autolathe variant 
It stops a bug that allows users to duplicate materials forever using an autolate (and its variants)
:cl:
fix: fixes a bug that allows infini-duplication using an autolathe 
/:cl:
=> Autolathe Patch

code/controllers/subsystems/dispatcher.dm
I put it in a wrong place and instead of properly sanitizing it, it also stripped all the required symbols :V
Bug feex yooo
:cl:
fix: fixes dispatcher breaking pings
/:cl:
=> Properly sanitizes dispatcher messages

code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm
Should fix that rare bug that somehow erases people's saves, so I don't have to restore backups.
Bruh 
:cl:
fix: THEORETICALLY fixes save erasure
/:cl:
=> Fixes pref runtimes

code/modules/client/preference_setup/augmentation/01_modifications.dm, code/modules/client/preference_setup/background/02_language.dm, code/modules/client/preference_setup/background/03_records.dm, code/modules/client/preference_setup/customization/01_ears.dm
Thanks to Jazz for pointing this out lmao
Lag spike bad
:cl:
fix: fixed loadout spam
/:cl:
=> Loadout improvement

maps/CEVEris/_CEV_Eris.dmm
Oopsie poopsie
Someone did a fucky wucky
The game compiles now lmao
:cl:
fix: Removes Horizon Class bluespace drive
/:cl:
=> Remove stashed commit

code/modules/client/preference_setup/loadout/lists/headwear.dm, code/modules/client/preference_setup/loadout/lists/suits.dm, code/modules/client/preference_setup/loadout/lists/uniforms.dm, code/modules/client/preference_setup/loadout/loadout.dm
Fixes the loadout failing to save/load. Fixes Nun's Outfit.
:cl:
fix: Fixes save/load/selection issues of loadout items.
/:cl:
=> Fixes loadout items

code/game/objects/structures/burrows.dm, code/modules/hydroponics/spreading/spacevines.dm
As a first part of improvements I've wanted to introduce to space vines, they shall no longer spawn or take burrows into maintenance to reduce the hardships of finding and destroying them.
Space vines are currently impossible to eliminate because they very often end up in maintenance and get a free base from which they can spread from forever.
With this PR, they will be barred from burrowing into or spawning in maintenance such that they can still be spread fairly quickly, but now crew can be expected to monitor crew areas to catch it spawning and having an AI can certainly help find where it is spreading.
Lastly, the only way they will be allowed to enter maintenance, as observed in testing, is to spread into it originating from a crew area.
:cl:
balance:  strange plants will no longer …
=> Vine spawn restrictions

code/modules/reagents/reagents/food-Drinks.dm
Makes certain beverages make more sense based on how much booze is actually in them
My sanity is draining and I wanted to make the alcohol 
Makes more sense
:cl:
tweak: tweaked the strength values of some drinks in hopes of making them make more sense
/:cl:
=> Makes alcoholic beverages make more sense

code/game/world.dm
Re-adds hub flair. I swear to god I did it some time ago, but it's just gone, apparently. 
Being identifiable on the hub good.
:cl:
add: Hub flair!
/:cl:
=> Re-adds hub flair

code/modules/sprite_accessories/_accessory_hair.dm
changes around some hair type names to make the classic Generic Ass Short Hair appear? maybe? works on my machine
i want my Generic Ass Short Hair, it's a core tenet of my plain human
:cl:
tweak: Theoretically readds Short Hair to the game, at the cost of renaming every other Short # variety to Short Hair #.
/:cl:
=> shuffles around some names to maybe make Short Hair 1 appear

code/game/gamemodes/roleset/simple.dm
Courtesy of @EvilJackCarver 
Fuck you *unmalfs you ai*
NANAKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
:cl:
fix: Malf AI now spawns only when crew is capable of handling it.
/:cl:
=> Fixes Malf AI spawning when it really shouldn't

code/game/jobs/whitelist.dm, code/modules/shield_generators/modes.dm
Ship got smaller, got less substations and one less turbine. Powerdrain chokes the ship.
I'm not sure if having to overclock SM to the point of immolation is a good way to meet power quota.
Admins can reload jobwhitelist.
:cl:
tweak: Lowers shield powerdrain
/:cl:
=> Reduces shield powerdrain and allows whitelist reload

maps/CEVEris/_CEV_Erida.dmm
Gave the AI core intercomms, since without them, the AI can merely scream in silence. Also cleaned up some areas outside in space that should not be not-space, such as "tcomsat", "AI core", and "AI foyer". And I set the telecomms SMES to automatically accept input because telecomms going off near the beginning of the round because the one way power has to go into it is kiiiinda silly. 
:cl:
tweak: The AI core has intercomms now
tweak: The telecomms SMES should have the input turned on automatically now
fix: Removed bad areas from space
/:cl:
=> AI core intercomms, small cleanups

nano/templates/shieldgen_eclipse.tmpl
I really need to clean out my copy of the code.
:cl:
fix: Fixes shield generator template not working.
/:cl:
=> Adds a file I forgot to include, like a fucking idiot

code/modules/client/preference_setup/loadout/lists/custom.dm, zzz_modular_eclipse/code/modules/custom_items/itemlist.dm
Adds custom item for sfox63
As above
:cl:
add: Adds custom item for contributor
/:cl:
=> Custom Item

code/game/jobs/job/church.dm
:cl:
fix: Changed cloner to Basin in custodian description.
/:cl:
=> Changed cloner to Basin in custodian description

code/modules/mob/living/simple_animal/vermin.dm
Partial refactor of Vermin ("Mimic") spawning behaviour.
Mimics currently have a north/south bias (they will attempt to replicate to the north or south before trying east or west), can spawn over open turfs (leading to situations where over fifteen thousand of them exist), and have no cap on power nutrition (meaning they can store enough power to spawn as many as it wants if a player carves their way through to one).
This fixes that.
refactor: Refactor of Vermin spawn code. 
fix: Vermin will no longer attempt to spawn more Vermin above open spaces.
fix: Vermin should no longer be biased north/south when they spawn a new Vermin. Any bias left is the result of inherent bias within the pick() proc.
fix: Vermin now have a cap of 80 "power nutrition", meaning if a player …
=> Partial refactor of vermin spawning behaviour

code/modules/mob/living/simple_animal/vermin.dm
Reworks vermin to be more spread out and spawn less. Some stats were tweaked to reflect reduced spawn rate.
:cl:
tweak: Vermin are more sneaky and less annoying
/:cl:
=> Vermin rework

code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm
Fixes #1692 
Stops transmutation from allowing players to spontaneously create an incredibly good rifle.
:cl:
tweak: Tweaked the contents of a homemade bolt rifle to stop them from spawning excelsior/other antag parts.
/:cl:
=> Transmutation fix

code/game/machinery/vending_eclipse.dm, maps/CEVEris/_CEV_Erida.dmm
Removes the courtroom, which was taking space due to the holodeck having a courtroom option. Replaces it with a public shooting range!
Gives a few chances at RP (shooting competition, anyone?), a chance for characters to practice their aim and shooting, and uses space that was otherwise being wasted.
:cl:
add: added in public shooting range
add: practice round Frozen Star vendor
del: removed the courtroom
/:cl:
Take a look at the new NEV Northern Light Shooting Range! Earmuffs, charging stations, and targets included.
=> Remove the courtroom

code/modules/mob/language/station.dm, code/modules/mob/living/carbon/superior_animal/giant_spider/types/nurse.dm, maps/CEVEris/_CEV_Erida.dmm, zzz_modular_eclipse/code/modules/mob/eris_spiders/phoron.dm
Moves the tables forward in the shooting range to avoid people hitting one another when going in and out, patched an issue with sol common not working properly, removed the invisible unhittable midwife that snuck in the code somehow, and patched a potential issue with not being able to kill the plasma spiders
No one likes unkillable spiders. No one. Bumping people who are shooting in the range may cause issues that would otherwise not arise with firing guns, and the patch for Sol Common stops it from breaking immersion.
:cl:
del: Deleted the unintended Midwife spider, which was invisible. Fun.
tweak: moved around some things in the public shooting range to prevent accidents
fix: Fixed a potential issue where plasmas would not explode
fix: Fixed the /list issue with sol common
/:cl:
=> Map Edits and Bugfixes

code/game/objects/structures/crates_lockers/closets/wardrobe.dm, code/modules/research/xenoarchaeology/finds/finds_misc.dm
Update to PR #1731 
:cl: 
del: Removed all code references to the talking crystal.
/:cl:
=> Talking Crystal hotfix

code/__HELPERS/icons.dm, code/datums/datacore.dm, code/datums/setup_option/backgrounds/origin.dm, code/game/machinery/doors/firedoor.dm, code/modules/admin/verbs/appearance_testing.dm, code/modules/client/preference_setup/general/02_body.dm, code/modules/client/preferences.dm, code/modules/core_implant/cruciform/machinery/cloning.dm, code/modules/examine/descriptions/firearms.dm, code/modules/mob/living/carbon/human/appearance.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/species/station/slime.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm, code/modules/mob/new_player/preferences_setup.dm, code/modules/organs/body_modifications.dm, code/modules/organs/external/organ_icon.dm, code/modules/projectiles/guns/projectile/battle_rifle/boltgun.dm, code/modules/sanity/sanity_mob.dm, zzz_modular_eclipse/code/modules/mob/eris_spiders/phoron.dm, zzz_modular_eclipse/code/modules/projectiles/guns/energy/paladin.dm, zzz_modular_eclipse/code/modules/projectiles/guns/energy/serenity.dm, zzz_modular_eclipse/code/modules/projectiles/guns/energy/squire.dm, zzz_modular_eclipse/code/modules/projectiles/guns/energy/tiandi.dm, zzz_modular_eclipse/code/modules/projectiles/guns/projectile/automatic/huangdi.dm, zzz_modular_eclipse/code/modules/projectiles/guns/projectile/automatic/olympus.dm, zzz_modular_eclipse/maverick_laser_rifle/code/maverick.dm
Let's try this again, without trying to push the commits to master like a doofus
- Changes several Origins to be lore compliant
- Alters how colours for hair, eyes, skin etc. are set to match changes upstream.
- Note to Jack, I had to comment out the "one_hand_penalty" description in the helptext, as I've yet to figure out how exactly our code is calculating a penalty for one handed guns right now.
:cl:
fix: fixed a few things
/:cl:
=> Val upstream

code/__HELPERS/icons.dm, code/datums/datacore.dm, code/modules/admin/verbs/appearance_testing.dm, code/modules/client/preference_setup/general/02_body.dm, code/modules/client/preferences.dm, code/modules/clothing/head/misc_special.dm, code/modules/core_implant/cruciform/machinery/cloning.dm, code/modules/core_implant/cruciform/modules.dm, code/modules/mob/living/carbon/human/appearance.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/species/station/slime.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/new_player/preferences_setup.dm, code/modules/nano/modules/human_appearance.dm, code/modules/organs/external/_external.dm, code/modules/organs/external/organ_icon.dm, code/modules/organs/internal/eyes.dm
Reverting changes to appearance vars. Still getting compile errors.
=> Upstream Fixes

code/__DEFINES/species_languages.dm, code/__HELPERS/global_lists.dm, code/game/gamemodes/events/ion_storm.dm, code/modules/aberrants/organs/machinery/disgorger.dm, code/modules/aberrants/organs/machinery/organ_fabricator.dm, code/modules/client/preference_setup/general/02_body.dm, code/modules/mob/living/carbon/human/appearance.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/mob/living/carbon/human/species/station/golem.dm, code/modules/mob/living/carbon/human/species/station/monkey.dm, code/modules/mob/living/carbon/human/species/station/skeleton.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/species/station/station_vr.dm, code/modules/mob/new_player/new_player.dm, code/modules/organs/blood.dm
This should make everything ready to merge.
=> Fixes Runtimes from Eris Merge + Species Spawning

code/controllers/configuration.dm
Disables the species whitelisting to allow players to join as any race.
We are an MRP/HRP server, and limiting species via whitelist is just.... unneeded.
Ran the code a few times as deadmin to make sure I could connect as a species and change my species to human. 
:cl:
fix: allowed players to once again play as any race.
/:cl:
=> Removes the whitelist to fix species

code/modules/mob/new_player/new_player.dm
This PR fixes the random name generators. 
It allows people to generate names once again for an idea, as opposed to simply giving them a blank name that cant be changed. 
tried to randomly generate names several times. It worked.
:cl:
fix: changed the data being fed into the random name generator so last names did not look for "gender" based last names.
/:cl:
=> Last Name Generator Fix

code/modules/mob/living/living.dm
This is for the DNA system - Missed a line when pushing, here it is!
I mean, you want fingerprints and DNA, right? Right?
:cl:
fix: initializes dna and fingerprints
/:cl:
=> Fixes DNA Initialization

code/modules/projectiles/gun.dm, zzz_modular_eclipse/code/modules/projectiles/guns/energy/tiandi.dm
Just a unrelated bug I noticed was in this codebase for some reason that was causing the integration tests to fail. I have done a fix on it.
```
[20:00:18] Runtime in gun.dm,169: Cannot execute 0.Copy().
proc name: Initialize (/obj/item/gun/Initialize)
src: the HM LHG M \"Mao\" (/obj/item/gun/energy/gun/mao)
src.loc: the military supply closet (/obj/structure/closet/random/milsupply)
call stack:
the HM LHG M \"Mao\" (/obj/item/gun/energy/gun/mao): Initialize(1)
the HM LHG M \"Mao\" (/obj/item/gun/energy/gun/mao): Initialize(1)
Atoms (/datum/controller/subsystem/atoms): InitAtom(the HM LHG M \"Mao\" (/obj/item/gun/energy/gun/mao), 0, /list (/list))
the HM LHG M \"Mao\" (/obj/item/gun/energy/gun/mao): New(1)
the random normal gun (/obj/spawner/gun/normal): spawn item()
the random normal gun …
```
=> Fixes Zoom Factor Runtime

code/modules/mob/floating_say.dm, code/modules/mob/living/say.dm
Removes Runechat from loading in the game
Prospective coders do not want to work on codebases that utilize Runechat. This should remove it to make it easier for them to work with.
I'm not gonna lie, I cannot run 514 servers on my machine. This is my test.
:cl:
del: Rmoved Runechat? 
server: something server ops should know
/:cl:
=> An attempt to remove Runechat for our prospective coders

code/game/machinery/antigrav.dm, code/game/machinery/recharger.dm, code/game/objects/items/weapons/nt_melee.dm, code/game/objects/items/weapons/sword_of_truth.dm, code/game/objects/structures/artwork_statue.dm
Rechargers now properly can be unbolted and the like by omni tools
Frameworking for other things such as antigrav, sword pedestal, and artwork to have set up for additional tool interactions  
closes #1589 
Being able to use tools fully is not as bad as the inverse
Also tested other changes in similar ways
:cl:
fix: Fixes some intractions with omni tools being non-functional
/:cl:
=> Fixes for some tool operations

maps/CEVEris/_CEV_Erida.dmm
fixes #1820
fixes #1821
- Fixes Broken Wintermutes in Sec Armoury.
- Fixes missing floor tile under Preacher's Quarters airlock.
Venting the ship to space when you open a door is generally considered a bad thing, or so I've been told. And I'm sure sec will appreciate having real firearms rather than debug items.
Compiled and tested on my own testing environment to confirm that the guns are spawning correctly and usable and that the floor has been fixed.
:cl:
fix: Replaced debug guns with wintermutes in sec armoury.
fix: Fixed missing floor under preacher's quarters airlock
/:cl:
=> Fix debug guns in armoury and missing floor tile in church

code/game/jobs/whitelist.dm
…rectly
Fixes a file to allow in-game whitelisting to work properly
People need to be able to play the game.
:cl:
code: refactored the location of the whitelist file in code to point to the proper location
/:cl:
=> Whitelist Patch

code/modules/multiz/map_data.dm
closes #1836 potentally
Fixes enforcer of technomancies saving. 
I assume this is the issue being told on the report.
:cl:
fix: Fixes enforcer of technomancies saving. 
/:cl:
=> Fixes Techno Enforcer saving
